//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stocktake.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class siixsem_stocktake_dbEntities : DbContext
    {
        public siixsem_stocktake_dbEntities()
            : base("name=siixsem_stocktake_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<getLabelST_Result> getLabelST(string model, string dj, string semi, string cgsroute, string qty, string qr, string mag)
        {
            var modelParameter = model != null ?
                new ObjectParameter("model", model) :
                new ObjectParameter("model", typeof(string));
    
            var djParameter = dj != null ?
                new ObjectParameter("dj", dj) :
                new ObjectParameter("dj", typeof(string));
    
            var semiParameter = semi != null ?
                new ObjectParameter("semi", semi) :
                new ObjectParameter("semi", typeof(string));
    
            var cgsrouteParameter = cgsroute != null ?
                new ObjectParameter("cgsroute", cgsroute) :
                new ObjectParameter("cgsroute", typeof(string));
    
            var qtyParameter = qty != null ?
                new ObjectParameter("qty", qty) :
                new ObjectParameter("qty", typeof(string));
    
            var qrParameter = qr != null ?
                new ObjectParameter("qr", qr) :
                new ObjectParameter("qr", typeof(string));
    
            var magParameter = mag != null ?
                new ObjectParameter("mag", mag) :
                new ObjectParameter("mag", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getLabelST_Result>("getLabelST", modelParameter, djParameter, semiParameter, cgsrouteParameter, qtyParameter, qrParameter, magParameter);
        }
    
        public virtual ObjectResult<getUserZone_Result> getUserZone(Nullable<int> idUser)
        {
            var idUserParameter = idUser.HasValue ?
                new ObjectParameter("idUser", idUser) :
                new ObjectParameter("idUser", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getUserZone_Result>("getUserZone", idUserParameter);
        }
    
        public virtual ObjectResult<insertLabel_Result> insertLabel(Nullable<int> idU, string serial, string model, string dj, string semi, string cgsroute, string qty, string qr, string mag)
        {
            var idUParameter = idU.HasValue ?
                new ObjectParameter("idU", idU) :
                new ObjectParameter("idU", typeof(int));
    
            var serialParameter = serial != null ?
                new ObjectParameter("serial", serial) :
                new ObjectParameter("serial", typeof(string));
    
            var modelParameter = model != null ?
                new ObjectParameter("model", model) :
                new ObjectParameter("model", typeof(string));
    
            var djParameter = dj != null ?
                new ObjectParameter("dj", dj) :
                new ObjectParameter("dj", typeof(string));
    
            var semiParameter = semi != null ?
                new ObjectParameter("semi", semi) :
                new ObjectParameter("semi", typeof(string));
    
            var cgsrouteParameter = cgsroute != null ?
                new ObjectParameter("cgsroute", cgsroute) :
                new ObjectParameter("cgsroute", typeof(string));
    
            var qtyParameter = qty != null ?
                new ObjectParameter("qty", qty) :
                new ObjectParameter("qty", typeof(string));
    
            var qrParameter = qr != null ?
                new ObjectParameter("qr", qr) :
                new ObjectParameter("qr", typeof(string));
    
            var magParameter = mag != null ?
                new ObjectParameter("mag", mag) :
                new ObjectParameter("mag", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<insertLabel_Result>("insertLabel", idUParameter, serialParameter, modelParameter, djParameter, semiParameter, cgsrouteParameter, qtyParameter, qrParameter, magParameter);
        }
    
        public virtual ObjectResult<updateChecked_Result> updateChecked(string qr)
        {
            var qrParameter = qr != null ?
                new ObjectParameter("qr", qr) :
                new ObjectParameter("qr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<updateChecked_Result>("updateChecked", qrParameter);
        }
    
        public virtual ObjectResult<getLastQtyByUser_Result> getLastQtyByUser(Nullable<int> idU)
        {
            var idUParameter = idU.HasValue ?
                new ObjectParameter("idU", idU) :
                new ObjectParameter("idU", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getLastQtyByUser_Result>("getLastQtyByUser", idUParameter);
        }
    
        public virtual ObjectResult<updateLastQtyByUser_Result> updateLastQtyByUser(Nullable<int> idU, Nullable<int> count)
        {
            var idUParameter = idU.HasValue ?
                new ObjectParameter("idU", idU) :
                new ObjectParameter("idU", typeof(int));
    
            var countParameter = count.HasValue ?
                new ObjectParameter("count", count) :
                new ObjectParameter("count", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<updateLastQtyByUser_Result>("updateLastQtyByUser", idUParameter, countParameter);
        }
    
        public virtual ObjectResult<getLastQtyByDJ_Result> getLastQtyByDJ(string dj)
        {
            var djParameter = dj != null ?
                new ObjectParameter("dj", dj) :
                new ObjectParameter("dj", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getLastQtyByDJ_Result>("getLastQtyByDJ", djParameter);
        }
    
        public virtual ObjectResult<updateLastQtyByDJ_Result> updateLastQtyByDJ(string dj, Nullable<int> count)
        {
            var djParameter = dj != null ?
                new ObjectParameter("dj", dj) :
                new ObjectParameter("dj", typeof(string));
    
            var countParameter = count.HasValue ?
                new ObjectParameter("count", count) :
                new ObjectParameter("count", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<updateLastQtyByDJ_Result>("updateLastQtyByDJ", djParameter, countParameter);
        }
    
        public virtual ObjectResult<getLabelMI_Result> getLabelMI(string model, string dj, string semi, string cgsroute, string qty, string qr, string mag)
        {
            var modelParameter = model != null ?
                new ObjectParameter("model", model) :
                new ObjectParameter("model", typeof(string));
    
            var djParameter = dj != null ?
                new ObjectParameter("dj", dj) :
                new ObjectParameter("dj", typeof(string));
    
            var semiParameter = semi != null ?
                new ObjectParameter("semi", semi) :
                new ObjectParameter("semi", typeof(string));
    
            var cgsrouteParameter = cgsroute != null ?
                new ObjectParameter("cgsroute", cgsroute) :
                new ObjectParameter("cgsroute", typeof(string));
    
            var qtyParameter = qty != null ?
                new ObjectParameter("qty", qty) :
                new ObjectParameter("qty", typeof(string));
    
            var qrParameter = qr != null ?
                new ObjectParameter("qr", qr) :
                new ObjectParameter("qr", typeof(string));
    
            var magParameter = mag != null ?
                new ObjectParameter("mag", mag) :
                new ObjectParameter("mag", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getLabelMI_Result>("getLabelMI", modelParameter, djParameter, semiParameter, cgsrouteParameter, qtyParameter, qrParameter, magParameter);
        }
    
        public virtual ObjectResult<insertLabelMI_Result> insertLabelMI(Nullable<int> idU, string serial, string model, string dj, string semi, string cgsroute, string qty, string qr, string mag)
        {
            var idUParameter = idU.HasValue ?
                new ObjectParameter("idU", idU) :
                new ObjectParameter("idU", typeof(int));
    
            var serialParameter = serial != null ?
                new ObjectParameter("serial", serial) :
                new ObjectParameter("serial", typeof(string));
    
            var modelParameter = model != null ?
                new ObjectParameter("model", model) :
                new ObjectParameter("model", typeof(string));
    
            var djParameter = dj != null ?
                new ObjectParameter("dj", dj) :
                new ObjectParameter("dj", typeof(string));
    
            var semiParameter = semi != null ?
                new ObjectParameter("semi", semi) :
                new ObjectParameter("semi", typeof(string));
    
            var cgsrouteParameter = cgsroute != null ?
                new ObjectParameter("cgsroute", cgsroute) :
                new ObjectParameter("cgsroute", typeof(string));
    
            var qtyParameter = qty != null ?
                new ObjectParameter("qty", qty) :
                new ObjectParameter("qty", typeof(string));
    
            var qrParameter = qr != null ?
                new ObjectParameter("qr", qr) :
                new ObjectParameter("qr", typeof(string));
    
            var magParameter = mag != null ?
                new ObjectParameter("mag", mag) :
                new ObjectParameter("mag", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<insertLabelMI_Result>("insertLabelMI", idUParameter, serialParameter, modelParameter, djParameter, semiParameter, cgsrouteParameter, qtyParameter, qrParameter, magParameter);
        }
    
        public virtual ObjectResult<updateCheckedMI_Result> updateCheckedMI(string qr)
        {
            var qrParameter = qr != null ?
                new ObjectParameter("qr", qr) :
                new ObjectParameter("qr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<updateCheckedMI_Result>("updateCheckedMI", qrParameter);
        }
    
        public virtual ObjectResult<getLabelInfoMI_Result> getLabelInfoMI(string label)
        {
            var labelParameter = label != null ?
                new ObjectParameter("label", label) :
                new ObjectParameter("label", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getLabelInfoMI_Result>("getLabelInfoMI", labelParameter);
        }
    
        public virtual ObjectResult<getLabelInfoST_Result> getLabelInfoST(string label)
        {
            var labelParameter = label != null ?
                new ObjectParameter("label", label) :
                new ObjectParameter("label", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getLabelInfoST_Result>("getLabelInfoST", labelParameter);
        }
    
        public virtual ObjectResult<updateQtyMagMI_Result> updateQtyMagMI(string label, Nullable<int> qty)
        {
            var labelParameter = label != null ?
                new ObjectParameter("label", label) :
                new ObjectParameter("label", typeof(string));
    
            var qtyParameter = qty.HasValue ?
                new ObjectParameter("qty", qty) :
                new ObjectParameter("qty", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<updateQtyMagMI_Result>("updateQtyMagMI", labelParameter, qtyParameter);
        }
    
        public virtual ObjectResult<updateQtyMagST_Result> updateQtyMagST(string label, Nullable<int> qty)
        {
            var labelParameter = label != null ?
                new ObjectParameter("label", label) :
                new ObjectParameter("label", typeof(string));
    
            var qtyParameter = qty.HasValue ?
                new ObjectParameter("qty", qty) :
                new ObjectParameter("qty", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<updateQtyMagST_Result>("updateQtyMagST", labelParameter, qtyParameter);
        }
    
        public virtual ObjectResult<updateCheckedPrintMI_Result> updateCheckedPrintMI(string qr)
        {
            var qrParameter = qr != null ?
                new ObjectParameter("qr", qr) :
                new ObjectParameter("qr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<updateCheckedPrintMI_Result>("updateCheckedPrintMI", qrParameter);
        }
    
        public virtual ObjectResult<updateCheckedPrintST_Result> updateCheckedPrintST(string qr)
        {
            var qrParameter = qr != null ?
                new ObjectParameter("qr", qr) :
                new ObjectParameter("qr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<updateCheckedPrintST_Result>("updateCheckedPrintST", qrParameter);
        }
    
        public virtual ObjectResult<getSerialSemPen_Result> getSerialSemPen(string fecha)
        {
            var fechaParameter = fecha != null ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getSerialSemPen_Result>("getSerialSemPen", fechaParameter);
        }
    
        public virtual ObjectResult<updateSemifinish_Result> updateSemifinish(string serial, string djGroup, string semi)
        {
            var serialParameter = serial != null ?
                new ObjectParameter("serial", serial) :
                new ObjectParameter("serial", typeof(string));
    
            var djGroupParameter = djGroup != null ?
                new ObjectParameter("djGroup", djGroup) :
                new ObjectParameter("djGroup", typeof(string));
    
            var semiParameter = semi != null ?
                new ObjectParameter("semi", semi) :
                new ObjectParameter("semi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<updateSemifinish_Result>("updateSemifinish", serialParameter, djGroupParameter, semiParameter);
        }
    }
}
